/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quantumx_HidConnection */

#ifndef _Included_quantumx_HidConnection
#define _Included_quantumx_HidConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     quantumx_HidConnection
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_quantumx_HidConnection_open
  (JNIEnv *, jobject);

/*
 * Class:     quantumx_HidConnection
 * Method:    eventLoopForever
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_quantumx_HidConnection_eventLoopForever
  (JNIEnv *, jobject);

/*
 * Class:     quantumx_HidConnection
 * Method:    getDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_quantumx_HidConnection_getDevices
  (JNIEnv *, jobject);

/*
 * Class:     quantumx_HidConnection
 * Method:    receiveMessage
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_quantumx_HidConnection_receiveMessage
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     quantumx_HidConnection
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_quantumx_HidConnection_sendMessage
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

/*
 * Class:     quantumx_HidConnection
 * Method:    getConsoleLog
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_quantumx_HidConnection_getConsoleLog
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
